### ISSUE TITLE
Model Checkpoints for Image-only

### ISSUE THREAD

**Issue by Road2Redemption** [mitvis/vistext#5]
Hello there! I have downloaded and unzipped the Benchmark Model Checkpoints in https://vis.csail.mit.edu/vistext/, but I didn't find the checkpoints for image-only ones, can you help me with that?
Because I want to predict without training and see the performance of the model with only images.
Here are all of the .pth files I have unzipped, there are mixed checkpoints but no image-only ones.
![屏幕截图 2023-10-24 105558](https://github.com/mitvis/vistext/assets/114891845/12c36050-7d98-4852-b9e7-b1d0bc3aaea7)

**Comment by aboggust** [comment]
Hi @Road2Redemption, thanks for your interest in VisText! 

We do not include the image-only model checkpoints because they produce inaccurate and low quality captions, and we do not suggest using them. Check out section 5.1 of [the paper](https://vis.csail.mit.edu/pubs/vistext.pdf) for more info on why our image-only models perform poorly.

If you are interested in the performance of our models on the VisText dataset, we report statistics in Table 1 of [the paper](https://vis.csail.mit.edu/pubs/vistext.pdf). Otherwise, if you would like to train your own image-only models, you can run [our training procedure](https://github.com/mitvis/vistext#model-training-evaluation-and-predictions) in `run.sh`

**Comment by Road2Redemption** [comment]
@aboggust I get it, thanks again!
